version: '3.6'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  elasticsearch:
    build: ./es
    ports:
      - 9200:9200

  python:
    build: ./python
    depends_on:
      - elasticsearch
    command: ["python","./Main.py"]


      


